### ISSUE TITLE
Cannot install module

### ISSUE THREAD

**Issue by newtrashcan** [sebj/homebridge-mac-temperature-light#2]
Hello. I am unable to install your plugin. Always got the same error (include log below), I am on SOX 10.10.5 (Yosemite). I would be glad if you can help. Thank you.

sudo npm install -g homebridge-mac-temperature-light

> homebridge-mac-temperature-light@1.0.0 install /usr/local/lib/node_modules/homebridge-mac-temperature-light
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/homebridge-mac-temperature-light/build'
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/homebridge-mac-temperature-light
gyp ERR! node -v v8.10.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! homebridge-mac-temperature-light@1.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the homebridge-mac-temperature-light@1.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xxx/.npm/_logs/2018-03-10T15_06_30_897Z-debug.log

**Comment by sebj** [comment]
I’m not exactly sure what could be causing this, so far I’ve tested this plugin with Node 9.5+ and Homebridge 0.4.32+, for what it’s worth.

Could you try running `sudo npm install —unsafe-perm --verbose -g homebridge-mac-temperature-light`, to see if the `—unsafe-perm` flag might help the installation?

If this doesn’t work, would you be able to upload a copy of the generated log file to [Pastebin.com](https://pastebin.com) or somewhere similar? (I see it mentions the log file path at the end of your log)
