### ISSUE TITLE
Dumb newb question, I'm sure...

### ISSUE THREAD

**Issue by barryl93** [sebj/homebridge-mac-temperature-light#4]
I installed this plugin to my existing Homebridge setup just fine, but I don't see the temp and light sensors showing up anywhere in Home.app. How do I make them appear? Where should I look for them?

Many thanks!

**Comment by sebj** [comment]
I'm not 100%, but if you've already added Homebridge to the Home app, you might be able to view details for the bridge (via 3D Touch or tap Edit then tap the bridge), then view accessories of the bridge, where the temp & light sensors may show up to be added. Let me know if that helps!

**Comment by barryl93** [comment]
Thanks for the quick response! I did try that, but sadly, only my original accessory shows up. I suspect that I've goofed up the syntax somehow. Here's the relevant portion of my config...

![voila_capture 2018-06-01_07-34-35_pm](https://user-images.githubusercontent.com/39839859/40867522-fa6ac2b0-65d2-11e8-9252-e7bde5ecdd0f.png)

**Comment by sebj** [comment]
The syntax in your config looks correct. The only other thing I could suggest would be to try to restart the Homebridge server or reboot the host device if you haven't already, beyond that I'd suggest you try searching or posting in the [Homebridge subreddit](https://www.reddit.com/r/homebridge), [Slack](https://slackin-znyruquwmv.now.sh/) or [Github Issues](https://github.com/nfarina/homebridge/issues).

**Comment by barryl93** [comment]
That seemed to do it. Thanks!
