### ISSUE TITLE
Request: Configurable scaling for temperature

### ISSUE THREAD

**Issue by Bluebie** [sebj/homebridge-mac-temperature-light#5]
Firstly, thanks so much for making this! It's a wonderful idea!

Second up, I'm running it on a mid 2010 mac mini, and it's registering about 5°C too warm. I note in the source code some comments suggesting calibration could be added. I'm very interested in this feature, and wondering how motivated @sebj is to implement such a thing?

**Comment by sebj** [comment]
Good suggestion, this is definitely doable. Meant to get to this before!
