### ISSUE TITLE
Can't install it on my Raspberry?

### ISSUE THREAD

**Issue by NagyAttilaORG** [sebj/homebridge-mac-temperature-light#6]
Hello!

As I see I can't install it on my Raspberry Pi, am I right?

`pi@raspberrypi:~ $ sudo npm install -g homebridge-mac-temperature-light
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for homebridge-mac-temperature-light@1.1.0: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: arm

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-12-14T07_02_53_277Z-debug.log`

It is sad.

**Comment by beeper99** [comment]
Its for Mac only - you need a different plugin
